/**
 * INGENIUM PRO - NÚCLEO DE CONSTANTES TÉCNICAS Y ECONÓMICAS V1.5
 * Moneda de Referencia: USD (Dólar Estadounidense)
 */

export const FISICA_BASE = {
    GRAVEDAD: 9.80665,
    PRESION_ATM_ESTANDAR: 101.325,
};

export const MATERIALES_RESISTENCIA = {
    ACERO_ESTRUCTURAL: {
        DENSIDAD: 7850,
        MODULO_YOUNG: 210000,
        LIMITE_FLUENCIA_ADMISIBLE: 235,
        COEF_DILATACION_TERMICA: 0.000012,
        COSTO_BASE_USD: 1500.00 // Por Tonelada
    },
    SUELOS_DENSIDAD_PROMEDIO: {
        ARCILLA_COMPACTA: 1800,
        ARENA_GRUESA: 1600,
        ROCA_SEDIMENTARIA: 2600
    }
};

export const COSTOS_OPERATIVOS_USD = {
    MANO_OBRA_OFICIAL_HORA: 25.00,
    EXCAVACION_M3_BASE: 45.00,
    PROTECCION_QUIMICA_M2: 120.00 // Recubrimiento ISO C5
};

export const FACTORES_AJUSTE = {
    DIFICULTAD_ARCILLA: 1.5,
    DIFICULTAD_ROCA: 2.2
};
